# Generated by Django 5.2.1 on 2025-09-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=260, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
