# Generated by Django 5.2.1 on 2025-09-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tag',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
